dist: trusty
sudo: required
env:
  - LLVM_CONFIG_PATH=/usr/lib/llvm-3.9/bin/llvm-config LIBCLANG_PATH=/usr/lib/x86_64-linux-gnu/ LIBCLANG_STATIC_PATH=/usr/lib/llvm-3.9/lib/ CLANG_PATH=/usr/bin/clang-3.9
before_install:
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
  - sudo apt-get -qq update
  - sudo apt-get install -y llvm-3.9-dev libclang-3.9-dev clang-3.9
install:
  - wget https://github.com/aquynh/capstone/archive/3.0.4.tar.gz
  - tar -xzvf 3.0.4.tar.gz
  - pushd capstone-3.0.4/ && make && sudo make install && popd

language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
