dist: trusty
sudo: required
install:
  - wget https://github.com/aquynh/capstone/archive/3.0.4.tar.gz
  - tar -xzvf 3.0.4.tar.gz
  - pushd capstone-3.0.4/ && make && sudo make install && popd

language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
